services:
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - '${DB_PORT}:3306'
        volumes:
            - ./mysql_data:/var/lib/mysql # MySQL 데이터 저장소 볼륨

volumes:
    mysql_data:
        driver: local
